/**
 * A prepared workspace on disk ready for an OpenCode generation run.
 *
 * Directory layout:
 *   /data/workspaces/{userId}/{projectId}/{jobId}/
 *     input/
 *       assets/    ← project assets (user uploads + platform-generated files)
 *       layer1/    ← HTML/CSS/JS artifacts from Layer 1 Chat Preview snapshot
 *       brief.md   ← auto-generated from conversation history
 *     output/      ← OpenCode writes the Astro.build project here
 *     logs/        ← stdout/stderr captured during OpenCode run
 *     MANIFEST.json
 */

export type WorkspaceFileSource =
    | "user_asset"       // copied from user-upload project asset
    | "platform_asset"   // copied from platform-generated project asset
    | "layer1_artifact"  // HTML / CSS / JS from PreviewSnapshot
    | "generated";       // generated by PrepareGenerationWorkspace (brief, manifest)

export interface WorkspaceFile {
    /** Path relative to the workspace root. */
    relativePath: string;
    source: WorkspaceFileSource;
    mimeType?: string;
    /** If sourced from a ProjectAsset, its id. */
    assetId?: string;
}

export interface GenerationWorkspace {
    /** Matches the Job id that will consume this workspace. */
    jobId: string;
    userId: string;
    projectId: string;
    /** Absolute fs path to workspace root. */
    rootPath: string;
    inputPath: string;
    outputPath: string;
    logsPath: string;
    /** All files staged for OpenCode. */
    files: WorkspaceFile[];
    /** Whether Layer 1 artifacts were included. */
    layer1Included: boolean;
    /** Absolute path to the generated brief.md, if created. */
    briefPath?: string;
    /** snapshotId used for Layer 1 artifacts, if applicable. */
    snapshotId?: string;
    createdAt: Date;
}
