/**
 * fanout-probe.ts — measures the section fan-out against a real provider.
 *
 * Exercises `GenerateSectionedArtifact` end to end and reports the acceptance criteria from
 * docs/specs/PARALLEL_SECTION_GENERATION_SPEC.md §8, against the recorded baseline of the run this
 * design exists to replace:
 *
 *   run f51ee098 — zai-org/GLM-5.3, preset slideshow, 2026-09-01
 *   629,546 ms · 32,768 completion tokens (the provider's cap) · journalled "succeeded" · truncated
 *
 * Usage:
 *   npm run fanout:probe -w apps/api
 *   FANOUT_PROVIDER=openrouter FANOUT_MODEL=deepseek/deepseek-v4-pro npm run fanout:probe -w apps/api
 *
 * Env:
 *   FANOUT_PROVIDER       optional, "siliconflow" (default) or "openrouter"
 *   FANOUT_MODEL          optional, defaults to the provider's own default below
 *   FANOUT_CONCURRENCY    optional, defaults to 4
 *   FANOUT_PLAN_TOKENS    optional, defaults to 6000
 *   FANOUT_SECTION_TOKENS optional, defaults to 4000
 *   FANOUT_OUT            optional path for the assembled HTML
 *   plus the chosen provider's key/base-url, read from .env or .env.docker
 *
 * Note on reasoning: `enable_thinking: false` is only honoured by SiliconFlow (see
 * chatRequestAdapter). Against OpenRouter the section calls still ask for no reasoning in prose, but
 * nothing enforces it — so a run there measures the fan-out's mechanics, not the reasoning split.
 *
 * This talks to a live provider and costs money. It is a probe, not a test.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import * as dotenv from "dotenv";

import { buildChatCompletionRequestBody } from "../application/llm/chatRequestAdapter";
import {
    GenerateSectionedArtifact,
    SectionPlanFailedError,
    type SectionLlmCall,
    type SectionLlmDispatcher,
    type SectionLlmReply,
} from "../application/use-cases/GenerateSectionedArtifact";

function findMonorepoRoot(): string {
    const cwd = process.cwd();
    if (fs.existsSync(path.join(cwd, "docker-compose.yml"))) return cwd;
    return path.resolve(__dirname, "../../../..");
}

const monorepoRoot = findMonorepoRoot();
// A dev checkout may carry either: `.env` for the dev stack, `.env.docker` for the deploy stack
// generated by install.sh. First one found wins, and neither overrides an already-exported value.
for (const candidate of [".env", ".env.docker"]) {
    const file = path.join(monorepoRoot, candidate);
    if (fs.existsSync(file)) dotenv.config({ path: file });
}

const PROVIDER = (process.env.FANOUT_PROVIDER?.trim() || "siliconflow").toLowerCase();
const CONCURRENCY = parseInt(process.env.FANOUT_CONCURRENCY ?? "4", 10);

const PROVIDERS: Record<string, { baseUrl: string; key: string; defaultModel: string }> = {
    siliconflow: {
        baseUrl: process.env.SILICONFLOW_BASE_URL ?? "https://api.siliconflow.com/v1",
        key: process.env.SILICONFLOW_API_KEY?.trim() ?? "",
        defaultModel: "MiniMaxAI/MiniMax-M2.5",
    },
    openrouter: {
        baseUrl: process.env.OPENROUTER_BASE_URL ?? "https://openrouter.ai/api/v1",
        // Both spellings are in use across this repo's env files.
        key: (process.env.OPEN_ROUTER_API_KEY ?? process.env.OPENROUTER_API_KEY)?.trim() ?? "",
        defaultModel: "deepseek/deepseek-v4-pro",
    },
};

const providerConfig = PROVIDERS[PROVIDER];
if (!providerConfig) {
    console.error(`Unknown FANOUT_PROVIDER "${PROVIDER}". Use one of: ${Object.keys(PROVIDERS).join(", ")}`);
    process.exit(1);
}

const BASE_URL = providerConfig.baseUrl.replace(/\/$/, "");
const API_KEY = providerConfig.key;
const MODEL = process.env.FANOUT_MODEL?.trim() || providerConfig.defaultModel;

if (!API_KEY) {
    console.error(`No API key for provider "${PROVIDER}". Set it in .env or .env.docker at the monorepo root.`);
    process.exit(1);
}

const DRY_RUN_PLAN = JSON.stringify({
    designTokens: { palette: ["#0f172a", "#f8fafc"], headingFont: "Inter", styleNote: "editoriale, molto spazio bianco" },
    sections: [
        { key: "situazione-attuale", title: "La situazione oggi", contentBrief: "Fotografa entrate, uscite fisse e risparmio residuo, senza giudizio.", charBudget: 1500 },
        { key: "obiettivi", title: "Gli obiettivi", contentBrief: "Tre obiettivi concreti a 1, 3 e 10 anni.", charBudget: 1200 },
    ],
});

// ── Baseline being replaced (run f51ee098) ───────────────────────────────────
const BASELINE = { durationMs: 629_546, completionTokens: 32_768, promptTokens: 13_938 };

class ChatCompletionsDispatcher implements SectionLlmDispatcher {
    constructor(private readonly model: string) { }

    async dispatch(call: SectionLlmCall): Promise<SectionLlmReply> {
        // FANOUT_DRY_RUN=1 prints the exact request each stage would send and dispatches nothing.
        // The point of the fan-out is what is in these two strings, so they have to be inspectable
        // without spending money to see them.
        if (process.env.FANOUT_DRY_RUN === "1") {
            console.log(`
${"═".repeat(78)}
${call.label}  maxTokens=${call.maxTokens}  disableThinking=${call.disableThinking}`);
            console.log(`── system (${call.system.length} chars) ──
${call.system}`);
            console.log(`── user (${call.user.length} chars) ──
${call.user}`);
            return {
                content: call.label === "plan" ? DRY_RUN_PLAN : "<section><h2>dry run</h2></section>",
                finishReason: "stop",
                usage: { promptTokens: 0, completionTokens: 0, totalTokens: 0 },
            };
        }

        const body = buildChatCompletionRequestBody({
            provider: PROVIDER,
            model: this.model,
            maxTokens: call.maxTokens,
            temperature: 0.4,
            enableThinking: !call.disableThinking,
            messages: [
                { role: "system", content: call.system },
                { role: "user", content: call.user },
            ],
        });

        const startedAt = Date.now();
        const res = await fetch(`${BASE_URL}/chat/completions`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                Authorization: `Bearer ${API_KEY}`,
            },
            body: JSON.stringify(body),
        });

        if (!res.ok) {
            const text = await res.text().catch(() => "");
            throw new Error(`provider ${res.status} on ${call.label}: ${text.slice(0, 300)}`);
        }

        const json = await res.json() as {
            choices?: Array<{
                finish_reason?: string;
                message?: { content?: string; reasoning_content?: string; reasoning?: string };
            }>;
            usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number };
        };

        const choice = json.choices?.[0];
        const reply: SectionLlmReply = {
            content: String(choice?.message?.content ?? ""),
            finishReason: choice?.finish_reason,
            reasoning: choice?.message?.reasoning_content ?? choice?.message?.reasoning,
            usage: {
                promptTokens: json.usage?.prompt_tokens ?? 0,
                completionTokens: json.usage?.completion_tokens ?? 0,
                totalTokens: json.usage?.total_tokens ?? 0,
            },
        };

        console.log(
            `  ${call.label.padEnd(26)} ${String(Date.now() - startedAt).padStart(6)}ms  ` +
            `out=${String(reply.usage?.completionTokens ?? 0).padStart(6)}  finish=${reply.finishReason ?? "?"}`,
        );
        return reply;
    }
}

// A brief of the same shape and ambition as the one that failed: a ten-section deck.
const BRIEF = `Brand: ARADIA — Piano Spese e Investimenti.
Un deck di presentazione in italiano, 10 sezioni, per presentare a una famiglia un piano di
gestione delle spese domestiche e di investimento graduale del risparmio residuo.
Tono: chiaro, concreto, rassicurante, senza gergo finanziario. Niente promesse di rendimento.
Deve coprire: situazione attuale, obiettivi, budget mensile, riduzione sprechi, fondo di emergenza,
orizzonte temporale, profilo di rischio, strumenti semplici, monitoraggio, prossimi passi.`;

const BASE_CONSTRAINTS = [
    "Write in Italian.",
    "Semantic HTML only. No frameworks, no external assets, no script tags.",
    "Each section is a self-contained <section> element.",
].join("\n");

async function main(): Promise<void> {
    console.log(`\nfan-out probe — ${PROVIDER} / ${MODEL} @ concurrency ${CONCURRENCY}\n`);

    const useCase = new GenerateSectionedArtifact(new ChatCompletionsDispatcher(MODEL));
    const startedAt = Date.now();

    let result;
    try {
        result = await useCase.execute({
            brief: BRIEF,
            deliverable: "a 10-section presentation deck",
            baseConstraints: BASE_CONSTRAINTS,
            concurrency: CONCURRENCY,
            planMaxTokens: parseInt(process.env.FANOUT_PLAN_TOKENS ?? "6000", 10),
            sectionMaxTokens: parseInt(process.env.FANOUT_SECTION_TOKENS ?? "4000", 10),
            sectionTimeoutMs: 120_000,
            totalTimeoutMs: 300_000,
            maxAttemptsPerSection: 2,
        }, (section) => {
            const mark = section.status === "generated" ? "ok" : "DEGRADED";
            console.log(`  → ${section.key} ${mark} (${section.durationMs}ms, ${section.attempts} attempt/s)`);
        });
    } catch (error) {
        if (error instanceof SectionPlanFailedError) {
            console.error("\nplan stage failed — raw reply follows:\n");
            console.error(error.raw);
            process.exit(2);
        }
        throw error;
    }

    const m = result.metrics;
    const checks: Array<[string, boolean, string]> = [
        ["no call over 8k completion tokens", m.maxCompletionTokensInOneCall <= 8000, `max ${m.maxCompletionTokensInOneCall}`],
        ["zero truncated calls", m.truncatedCalls === 0, `${m.truncatedCalls} truncated`],
        ["wall clock under 2 minutes", m.totalDurationMs < 120_000, `${(m.totalDurationMs / 1000).toFixed(1)}s`],
        ["all sections generated", m.placeholders === 0, `${m.placeholders} placeholder/s`],
        ["input tokens under 40k", m.promptTokens < 40_000, `${m.promptTokens}`],
        ["first section under 20s", (m.firstSectionMs ?? Infinity) < 20_000, `${((m.firstSectionMs ?? 0) / 1000).toFixed(1)}s`],
        ["plan parsed without repair", !m.planWasRepaired, m.planWasRepaired ? "repaired" : "clean"],
    ];

    console.log(`\n─── acceptance (spec §8) ────────────────────────────────────`);
    for (const [label, pass, detail] of checks) {
        console.log(`  ${pass ? "PASS" : "FAIL"}  ${label.padEnd(34)} ${detail}`);
    }

    console.log(`\n─── vs baseline f51ee098 ────────────────────────────────────`);
    console.log(`  wall clock        ${(m.totalDurationMs / 1000).toFixed(1)}s   vs  ${(BASELINE.durationMs / 1000).toFixed(1)}s   (${(BASELINE.durationMs / Math.max(m.totalDurationMs, 1)).toFixed(1)}x faster)`);
    console.log(`  completion tokens ${m.completionTokens}   vs  ${BASELINE.completionTokens}`);
    console.log(`  prompt tokens     ${m.promptTokens}   vs  ${BASELINE.promptTokens}`);
    console.log(`  calls             ${m.calls}   vs  1`);
    console.log(`  sections          ${result.sections.length} (${m.placeholders} degraded)`);
    console.log(`  plan stage        ${(m.planDurationMs / 1000).toFixed(1)}s`);

    const outPath = process.env.FANOUT_OUT
        ?? path.join(monorepoRoot, "debug", `fanout-${MODEL.replace(/\W+/g, "-")}-${Date.now()}.html`);
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, `<!doctype html><meta charset="utf-8"><title>fan-out probe</title>\n${result.html}\n`, "utf8");
    console.log(`\n  artifact → ${outPath}`);
    console.log(`  elapsed  → ${((Date.now() - startedAt) / 1000).toFixed(1)}s\n`);

    process.exit(checks.every(([, pass]) => pass) ? 0 : 1);
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
